# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Concurrent Pascal for Microcontrollers
sub-title: >
             Cooperating Sequential Processes 
             <ul>
                 <li>Language supported</li>
                 <li>Interrupt driven</li>
                 <li>Multi-priority</li>
                 <li>Monitors for inter-process communication</li>
             </ul>
repository_url: https://github.com/dhawk/concurrent-pascal-compiler 
email: cp@davidhawk.us
description: > # this means to ignore newlines until "baseurl:"
  Language Supported Interrupt Driven Multi-Priority Concurrent Processes
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  dhawk

# Build settings
highlighter: rouge

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    disable: true

